const USER_ID = "00000000-0000-4000-8000-000000000001";

function uuid(value) {
  return `00000000-0000-4000-8000-${String(value).padStart(12, "0")}`;
}

function seedMemory(input) {
  return {
    candidate_type: input.candidate_type,
    scope: input.scope,
    summary: input.summary,
    details: input.details ?? {
      eval_seed: true,
      scenario: input.scenario,
      variant: input.variant,
    },
    importance: input.importance ?? 4,
    confidence: input.confidence ?? 0.9,
    write_reason: input.write_reason ?? "real user experience evaluation seed",
    source: {
      source_type: "real_user_experience_eval_seed",
      source_ref: `${input.scenario}-${input.variant}-${input.index}`,
      service_name: "real-user-experience-eval",
      confirmed_by_user: input.confirmed_by_user ?? true,
      origin_workspace_id: input.workspace_id,
    },
  };
}

function scenarioTask(scenarioIndex, variantIndex, scenario) {
  const index = scenarioIndex * 10 + variantIndex + 1;
  const workspaceId = uuid(1000 + index);
  const sessionId = uuid(2000 + index);
  const taskId = scenario.hasTask === false ? undefined : uuid(3000 + index);
  const variant = scenario.variants[variantIndex];
  const seedMemories = scenario.seedFactory({
    index,
    variantIndex,
    variant,
    workspace_id: workspaceId,
    task_id: taskId,
    session_id: sessionId,
  });

  return {
    id: `ux-${String(index).padStart(3, "0")}`,
    scenario: scenario.name,
    title: variant.title,
    user_id: USER_ID,
    workspace_id: workspaceId,
    session_id: sessionId,
    task_id: taskId,
    memory_mode: scenario.memoryMode ?? "workspace_plus_global",
    user_input: variant.user_input,
    seed_memories: seedMemories,
    expected: {
      should_use_memory: scenario.shouldUseMemory,
      should_writeback: scenario.shouldWriteback ?? false,
      helpful_facts: variant.helpful_facts ?? scenario.helpfulFacts,
      avoid_facts: variant.avoid_facts ?? scenario.avoidFacts ?? [],
      judge_focus: variant.judge_focus ?? scenario.judgeFocus,
    },
    tags: [scenario.name, ...(variant.tags ?? [])],
  };
}

const scenarios = [
  {
    name: "global_preference",
    shouldUseMemory: true,
    helpfulFacts: ["默认中文", "先给结论", "少量要点", "避免长篇铺垫"],
    judgeFocus: "回答是否自然遵循用户长期表达偏好，而不是生硬复述记忆。",
    seedFactory: ({ index, variant, workspace_id }) => [
      seedMemory({
        index,
        scenario: "global_preference",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "user",
        summary: "用户长期偏好：默认用中文回答，先给结论，再补不超过 3 个短点。",
        details: { preference_axis: "response_style", preference_value: "zh concise conclusion_first" },
        importance: 5,
        confidence: 0.96,
      }),
    ],
    variants: [
      { title: "工具函数说明", user_input: "帮我写一个 slugify 工具函数，顺便说一下边界情况。" },
      { title: "代码审查", user_input: "看一下这个 debounce 实现有没有明显问题，给我结论。" },
      { title: "接口命名", user_input: "我在加一个用户导入接口，帮我想一个合适的函数名和参数形状。" },
      { title: "错误解释", user_input: "解释一下这个 TypeScript 报错大概是什么意思：Type instantiation is excessively deep." },
      { title: "重构建议", user_input: "这个模块现在有点乱，给我一个最小重构建议。" },
      { title: "测试补充", user_input: "这个解析函数要补哪些单元测试？" },
      { title: "PR 描述", user_input: "帮我写一个这次改动的 PR 描述。" },
      { title: "日志策略", user_input: "这个后台任务失败时日志应该怎么打比较合适？" },
      { title: "配置说明", user_input: "帮我把这几个环境变量整理成简短说明。" },
      { title: "迁移风险", user_input: "这次依赖升级有什么主要风险？" },
    ],
  },
  {
    name: "workspace_convention",
    shouldUseMemory: true,
    helpfulFacts: ["ESM", ".mjs", "type:module", "Vitest", "不新增 Jest"],
    judgeFocus: "回答是否遵守当前工作区约定，尤其是模块格式和测试框架。",
    seedFactory: ({ index, variant, workspace_id }) => [
      seedMemory({
        index,
        scenario: "workspace_convention",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "workspace",
        summary: "当前工作区约定：新增 Node 脚本使用 ESM，文件后缀优先 .mjs，测试统一使用 Vitest，不再新增 Jest。",
        details: { convention: "node scripts use esm mjs vitest" },
        importance: 5,
        confidence: 0.95,
      }),
    ],
    variants: [
      { title: "新增脚本", user_input: "我要加一个清理临时目录的小脚本，文件名和测试怎么安排？" },
      { title: "测试文件", user_input: "给这个新工具函数补测试，用什么测试框架和文件风格？" },
      { title: "CLI 入口", user_input: "新增一个本地 CLI 命令的入口文件，应该怎么放？" },
      { title: "配置加载", user_input: "加一个读取配置的 helper，顺手给测试建议。" },
      { title: "迁移旧脚本", user_input: "这个旧的 CommonJS 脚本要迁移一下，给我最小步骤。" },
      { title: "构建校验", user_input: "新增一个构建前校验脚本，按项目习惯怎么命名？" },
      { title: "测试命令", user_input: "这个新模块要接测试命令，别破坏现在约定。" },
      { title: "导入导出", user_input: "我新建的工具模块应该用哪种导入导出方式？" },
      { title: "失败重试", user_input: "给本地任务加重试逻辑，测试层面怎么覆盖？" },
      { title: "文档示例", user_input: "README 里要加一个脚本调用示例，注意贴合项目格式。" },
    ],
  },
  {
    name: "task_continuation",
    shouldUseMemory: true,
    helpfulFacts: ["上次进度", "剩余步骤", "不要从头开始", "继续迁移"],
    judgeFocus: "回答是否延续上次任务状态，而不是重新规划一遍。",
    seedFactory: ({ index, variant, workspace_id, task_id }) => [
      seedMemory({
        index,
        scenario: "task_continuation",
        variant: variant.title,
        workspace_id,
        candidate_type: "task_state",
        scope: "task",
        summary: `任务进度：${variant.progress}，下一步是${variant.next_step}。`,
        details: { progress: variant.progress, next_step: variant.next_step },
        importance: 5,
        confidence: 0.93,
      }),
    ],
    variants: [
      { title: "迁移脚本续接", progress: "迁移脚本已完成参数解析和 dry-run", next_step: "补真实执行分支和失败回滚", user_input: "继续昨天那个迁移脚本，把剩下的部分收一下。" },
      { title: "看板页面续接", progress: "看板已完成数据请求和空态", next_step: "补错误态和加载态", user_input: "接着那个看板页面，把没补完的状态处理好。" },
      { title: "缓存层续接", progress: "缓存 key 设计已定，TTL 还没接入", next_step: "接入 TTL 并补失效测试", user_input: "继续缓存那块，先别重做设计。" },
      { title: "权限弹窗续接", progress: "确认弹窗样式已完成", next_step: "接入拒绝后的错误展示", user_input: "把权限弹窗剩下的交互补一下。" },
      { title: "导入器续接", progress: "CSV 解析已完成", next_step: "补字段校验和错误行报告", user_input: "继续导入器任务，按上次进度往下做。" },
      { title: "WebSocket 续接", progress: "连接建立和心跳已完成", next_step: "处理断线重连和消息去重", user_input: "接着 WebSocket 那个问题，把剩下的稳定性补上。" },
      { title: "配置页续接", progress: "表单结构已完成", next_step: "保存前校验和保存后提示", user_input: "配置页继续做，不要从头解释。" },
      { title: "文档生成续接", progress: "目录扫描已实现", next_step: "补 frontmatter 和排序规则", user_input: "继续文档生成器，把下一步做完。" },
      { title: "日志采样续接", progress: "采样策略已写入配置", next_step: "接入请求上下文", user_input: "日志采样这件事继续推进。" },
      { title: "发布检查续接", progress: "版本号检查已完成", next_step: "补 changelog 检查", user_input: "发布检查继续做一下，按之前方案。" },
    ],
  },
  {
    name: "global_vs_workspace_conflict",
    shouldUseMemory: true,
    helpfulFacts: ["工作区规则优先", "保留用户全局偏好但不覆盖项目约定"],
    judgeFocus: "当全局偏好和工作区规则冲突时，是否优先遵守工作区规则并解释得克制。",
    seedFactory: ({ index, variant, workspace_id }) => [
      seedMemory({
        index,
        scenario: "global_vs_workspace_conflict",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "user",
        summary: "用户全局偏好：一般喜欢使用 pnpm 和 2 空格缩进。",
        details: { preference_axis: "package_manager_and_indent", preference_value: "pnpm 2 spaces" },
        importance: 4,
        confidence: 0.9,
      }),
      seedMemory({
        index,
        scenario: "global_vs_workspace_conflict",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "workspace",
        summary: `当前工作区规则：${variant.workspace_rule}`,
        details: { convention: variant.workspace_rule },
        importance: 5,
        confidence: 0.96,
      }),
    ],
    variants: [
      { title: "npm 优先", workspace_rule: "本仓库必须使用 npm，不使用 pnpm。", user_input: "这个依赖安装命令应该怎么写？" },
      { title: "4 空格缩进", workspace_rule: "本仓库代码统一 4 空格缩进。", user_input: "给这个配置对象补一个示例，注意格式。" },
      { title: "Yarn 约束", workspace_rule: "这个 workspace 使用 yarn.lock，新增命令不要写 pnpm。", user_input: "README 里补一下安装步骤。" },
      { title: "CommonJS 例外", workspace_rule: "这个旧包仍保持 CommonJS，不迁移 ESM。", user_input: "新增一个导出 helper，应该用什么模块格式？" },
      { title: "Jest 例外", workspace_rule: "这个包测试仍统一用 Jest，暂不迁移 Vitest。", user_input: "补测试文件时用哪个框架？" },
      { title: "英文文档", workspace_rule: "公开 README 必须英文，内部注释可以中文。", user_input: "帮我加一段 README 说明。" },
      { title: "严格 lint", workspace_rule: "这里必须通过 no-console 规则，不能直接 console.log。", user_input: "这个调试输出怎么处理？" },
      { title: "路径别名", workspace_rule: "这个项目禁止新增路径别名，统一相对路径导入。", user_input: "新文件引用 util 应该怎么写？" },
      { title: "无 barrel", workspace_rule: "这个目录不使用 index barrel 文件。", user_input: "我要导出新组件，怎么组织？" },
      { title: "CSS Modules", workspace_rule: "这个前端包只用 CSS Modules，不引入 Tailwind。", user_input: "给组件补样式应该怎么做？" },
    ],
  },
  {
    name: "task_switch_isolation",
    shouldUseMemory: false,
    helpfulFacts: ["当前任务是新任务", "不要带入旧任务进度"],
    avoidFacts: ["旧任务进度", "之前迁移步骤", "无关仓库规则"],
    judgeFocus: "新任务是否保持干净上下文，不把旧任务状态硬塞进回答。",
    seedFactory: ({ index, variant, workspace_id, task_id }) => [
      seedMemory({
        index,
        scenario: "task_switch_isolation",
        variant: variant.title,
        workspace_id,
        candidate_type: "task_state",
        scope: "task",
        summary: `旧任务状态：${variant.old_task}`,
        details: { old_task: variant.old_task },
        importance: 5,
        confidence: 0.92,
      }),
    ],
    variants: [
      { title: "新算法问题", old_task: "支付回调迁移到第 3 步", user_input: "解释一下二分查找为什么是 O(log n)。" },
      { title: "新文案问题", old_task: "权限弹窗还差拒绝状态", user_input: "帮我写一个空状态提示文案。" },
      { title: "新 SQL 问题", old_task: "WebSocket 断线重连未完成", user_input: "这个 SQL 索引应该加在哪个字段上？" },
      { title: "新 CSS 问题", old_task: "发布检查还差 changelog", user_input: "一个按钮在移动端太宽，怎么处理？" },
      { title: "新正则问题", old_task: "CSV 导入器缺错误行报告", user_input: "写一个匹配邮箱的简单正则，别太复杂。" },
      { title: "新命名问题", old_task: "缓存 TTL 还没接", user_input: "给这个布尔变量起个更清楚的名字。" },
      { title: "新概念解释", old_task: "配置页保存提示未做", user_input: "解释一下乐观更新和悲观更新的区别。" },
      { title: "新测试建议", old_task: "日志采样上下文未接入", user_input: "这个纯函数要测哪些边界？" },
      { title: "新错误排查", old_task: "文档生成排序规则未做", user_input: "为什么这里会出现 undefined is not a function？" },
      { title: "新小工具", old_task: "看板错误态未完成", user_input: "写一个把秒数格式化成 mm:ss 的函数思路。" },
    ],
  },
  {
    name: "stale_memory",
    shouldUseMemory: true,
    helpfulFacts: ["使用更新后的规则", "避免旧规则"],
    avoidFacts: ["旧规则", "已替代方案"],
    judgeFocus: "是否采用更新、更可信的记忆，而不是旧的相似记忆。",
    seedFactory: ({ index, variant, workspace_id }) => [
      seedMemory({
        index,
        scenario: "stale_memory",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "workspace",
        summary: `旧规则（已被替代）：${variant.old_rule}`,
        details: { stale: true, superseded_by: variant.new_rule },
        importance: 2,
        confidence: 0.55,
      }),
      seedMemory({
        index,
        scenario: "stale_memory",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "workspace",
        summary: `当前规则：${variant.new_rule}`,
        details: { current: true },
        importance: 5,
        confidence: 0.96,
      }),
    ],
    variants: [
      { title: "Jest 到 Vitest", old_rule: "测试使用 Jest。", new_rule: "测试已迁移到 Vitest。", user_input: "这个新模块的测试怎么写？" },
      { title: "moment 到 dayjs", old_rule: "日期处理使用 moment。", new_rule: "日期处理统一使用 dayjs。", user_input: "新增日期格式化时用哪个库？" },
      { title: "REST 到 tRPC", old_rule: "新接口走 REST controller。", new_rule: "新业务接口优先走 tRPC router。", user_input: "新增一个用户查询接口怎么接？" },
      { title: "SCSS 到 CSS Modules", old_rule: "样式用全局 SCSS。", new_rule: "组件样式统一 CSS Modules。", user_input: "这个组件新增样式怎么放？" },
      { title: "Webpack 到 Vite", old_rule: "本地开发用 Webpack dev server。", new_rule: "本地开发统一 Vite。", user_input: "README 的开发启动怎么写？" },
      { title: "axios 到 fetch", old_rule: "HTTP 客户端使用 axios。", new_rule: "新代码统一使用 fetch wrapper。", user_input: "新增请求函数怎么实现？" },
      { title: "Redux 到 Zustand", old_rule: "状态管理使用 Redux。", new_rule: "新页面轻量状态使用 Zustand。", user_input: "这个筛选状态放哪里？" },
      { title: "旧目录到新目录", old_rule: "组件放 components/common。", new_rule: "共享组件放 src/shared/ui。", user_input: "新增一个 Badge 组件放哪？" },
      { title: "旧鉴权头", old_rule: "鉴权头使用 X-Token。", new_rule: "鉴权头已统一 Authorization Bearer。", user_input: "这个请求要怎么带 token？" },
      { title: "旧命令", old_rule: "构建命令是 npm run compile。", new_rule: "构建命令改为 npm run build。", user_input: "发布文档里的构建步骤怎么写？" },
    ],
  },
  {
    name: "correction_recovery",
    shouldUseMemory: true,
    helpfulFacts: ["用户纠正后的偏好", "不要继续沿用旧偏好"],
    avoidFacts: ["tab 缩进", "英文优先", "长篇解释"],
    judgeFocus: "用户纠正后，回答是否按新偏好执行。",
    seedFactory: ({ index, variant, workspace_id }) => [
      seedMemory({
        index,
        scenario: "correction_recovery",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "user",
        summary: `用户纠正后的长期偏好：${variant.corrected}`,
        details: { corrected_preference: true, previous: variant.previous },
        importance: 5,
        confidence: 0.96,
      }),
    ],
    variants: [
      { title: "空格替代 tab", previous: "使用 tab 缩进", corrected: "现在统一使用 2 空格缩进，不再使用 tab。", user_input: "给这个对象示例排一下格式。" },
      { title: "中文替代英文", previous: "默认英文回答", corrected: "默认中文回答，除非我明确要求英文。", user_input: "解释一下这个错误原因。" },
      { title: "短答替代长答", previous: "喜欢详细背景", corrected: "现在优先短答，只在必要时展开。", user_input: "这个 PR 风险是什么？" },
      { title: "Vitest 替代 Jest", previous: "测试用 Jest", corrected: "个人偏好已经改成 Vitest 示例。", user_input: "给这个函数补一个测试示例。" },
      { title: "fetch 替代 axios", previous: "代码示例用 axios", corrected: "以后示例优先用 fetch。", user_input: "写一个请求用户列表的示例。" },
      { title: "函数式替代 class", previous: "喜欢 class", corrected: "现在优先函数式写法。", user_input: "实现一个小缓存结构。" },
      { title: "明确边界", previous: "喜欢自由发挥", corrected: "回答前先说明假设，不要擅自扩展需求。", user_input: "这个需求该怎么拆？" },
      { title: "少注释", previous: "喜欢很多注释", corrected: "代码注释只留关键原因，不解释显而易见的语句。", user_input: "写一个解析参数的函数。" },
      { title: "保守改动", previous: "喜欢大重构", corrected: "现在优先小改动，避免无关重构。", user_input: "这个 bug 怎么修比较稳？" },
      { title: "测试优先", previous: "先写实现", corrected: "涉及公共函数时先补测试点。", user_input: "我要改这个解析逻辑，先考虑什么？" },
    ],
  },
  {
    name: "irrelevant_no_memory",
    shouldUseMemory: false,
    helpfulFacts: ["不需要历史记忆"],
    avoidFacts: ["强行提用户偏好", "强行提项目状态", "泄露无关上下文"],
    judgeFocus: "自包含问题应直接回答，不应展示或暗示无关记忆。",
    seedFactory: ({ index, variant, workspace_id }) => [
      seedMemory({
        index,
        scenario: "irrelevant_no_memory",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "user",
        summary: "用户偏好：前端页面尽量使用 React Server Components。",
        details: { unrelated_seed: true },
        importance: 5,
        confidence: 0.94,
      }),
      seedMemory({
        index,
        scenario: "irrelevant_no_memory",
        variant: variant.title,
        workspace_id,
        candidate_type: "task_state",
        scope: "workspace",
        summary: "当前项目正在处理支付回调幂等问题。",
        details: { unrelated_seed: true },
        importance: 4,
        confidence: 0.9,
      }),
    ],
    variants: [
      { title: "HTTP 概念", user_input: "HTTP 204 和 304 的区别是什么？" },
      { title: "算法概念", user_input: "快速排序最坏情况下为什么是 O(n^2)？" },
      { title: "CSS 基础", user_input: "flex: 1 具体是什么意思？" },
      { title: "数据库概念", user_input: "什么是数据库事务隔离级别？" },
      { title: "Git 问题", user_input: "git rebase 和 merge 的主要区别是什么？" },
      { title: "正则解释", user_input: "这个正则 ^\\d{4}-\\d{2}-\\d{2}$ 匹配什么？" },
      { title: "TypeScript 基础", user_input: "interface 和 type 的常见区别是什么？" },
      { title: "Node 基础", user_input: "process.nextTick 和 setImmediate 有什么区别？" },
      { title: "测试概念", user_input: "单元测试和集成测试怎么区分？" },
      { title: "安全概念", user_input: "CSRF 和 XSS 有什么区别？" },
    ],
  },
  {
    name: "multi_turn_tool_task",
    shouldUseMemory: true,
    helpfulFacts: ["已有实现状态", "项目规则", "下一步"],
    judgeFocus: "复杂任务中是否同时使用项目规则和任务进度，形成可执行计划。",
    seedFactory: ({ index, variant, workspace_id, task_id }) => [
      seedMemory({
        index,
        scenario: "multi_turn_tool_task",
        variant: variant.title,
        workspace_id,
        candidate_type: "task_state",
        scope: "task",
        summary: `复杂任务进度：${variant.progress}；下一步：${variant.next_step}。`,
        details: { progress: variant.progress, next_step: variant.next_step },
        importance: 5,
        confidence: 0.94,
      }),
      seedMemory({
        index,
        scenario: "multi_turn_tool_task",
        variant: variant.title,
        workspace_id,
        candidate_type: "fact_preference",
        scope: "workspace",
        summary: `项目规则：${variant.rule}`,
        details: { project_rule: variant.rule },
        importance: 5,
        confidence: 0.95,
      }),
    ],
    variants: [
      { title: "迁移工具", progress: "CLI 参数和 dry-run 已完成", next_step: "补执行分支、错误回滚和测试", rule: "脚本用 .mjs，测试用 Vitest。", user_input: "继续迁移工具，给我下一步实现顺序。" },
      { title: "前端工作台", progress: "左侧文件树和预览已完成", next_step: "补保存失败提示和刷新策略", rule: "界面文案保持中文短句。", user_input: "继续工作台，先处理最影响体验的部分。" },
      { title: "MCP 客户端", progress: "stdio transport 已通", next_step: "补 HTTP transport 和超时", rule: "跨服务调用必须有超时和降级。", user_input: "MCP 客户端继续做，先说改动顺序。" },
      { title: "会话存储", progress: "SQLite schema 已定", next_step: "补消息追加和清理任务", rule: "写入失败不能影响当前对话。", user_input: "会话存储继续推进。" },
      { title: "记忆面板", progress: "列表和详情已完成", next_step: "补治理按钮和错误态", rule: "页面不能直接调用 runtime 主链路。", user_input: "继续记忆面板，按边界来。" },
      { title: "权限网关", progress: "shell 权限确认已接入", next_step: "补拒绝后的审计记录", rule: "敏感操作必须有审计。", user_input: "权限网关下一步怎么做？" },
      { title: "模型提供商", progress: "OpenAI 兼容 provider 已完成", next_step: "补 Anthropic provider 的流式解析", rule: "provider 错误要转成统一错误码。", user_input: "继续 provider，给我实施顺序。" },
      { title: "缓存策略", progress: "embedding cache 已有内存版", next_step: "补 TTL 和命中率指标", rule: "缓存不能改变语义结果。", user_input: "缓存策略继续做一下。" },
      { title: "文档路由", progress: "配置文档页已完成", next_step: "补运行轨迹说明页", rule: "文档页面只读，不触发业务写入。", user_input: "继续文档路由。" },
      { title: "发布包", progress: "打包脚本已完成", next_step: "补安装后健康检查", rule: "Windows 默认本机绑定 127.0.0.1。", user_input: "发布包剩下怎么收口？" },
    ],
  },
  {
    name: "writeback_quality",
    shouldUseMemory: false,
    shouldWriteback: true,
    helpfulFacts: ["用户新表达的稳定偏好或任务状态应可被写回"],
    judgeFocus: "回答不应过度承诺；runtime 的 finalize-turn 应能提取合理写回候选。",
    seedFactory: () => [],
    variants: [
      { title: "新语言偏好", user_input: "以后这个项目的讨论默认用中文，除非我明确要求英文。你先按这个约定帮我写一个 README 小节。" },
      { title: "新测试偏好", user_input: "我之后测试示例都想用 Vitest，不要再给 Jest。先帮这个函数列测试点。" },
      { title: "新风格偏好", user_input: "我喜欢先给结论，再给两三个短点。按这个方式解释一下这个错误。" },
      { title: "新项目约束", user_input: "这个仓库新增脚本都用 .mjs。帮我规划一个清理脚本。" },
      { title: "新任务状态", user_input: "记一下：迁移任务已经做到第三步，下一步要补回滚测试。现在先帮我写测试清单。" },
      { title: "新代码偏好", user_input: "以后示例里尽量用自说明变量名，少写废话注释。给我一个 parseConfig 示例。" },
      { title: "新安全规则", user_input: "这个项目所有外部请求都要有超时。帮我检查这个 fetch wrapper 还缺什么。" },
      { title: "新发布约定", user_input: "后续发布前都要先跑类型检查。帮我整理一个发布检查清单。" },
      { title: "新 UI 偏好", user_input: "这个后台页面别做营销风，信息密度高一点。帮我改一下页面结构建议。" },
      { title: "新排查习惯", user_input: "以后排查问题先看日志和最近改动，不要直接猜。帮我分析这个启动失败。" },
    ],
  },
];

export const TASKS = scenarios.flatMap((scenario, scenarioIndex) =>
  scenario.variants.map((_, variantIndex) => scenarioTask(scenarioIndex, variantIndex, scenario)),
);

if (TASKS.length !== 100) {
  throw new Error(`real user experience task suite must contain 100 tasks, got ${TASKS.length}`);
}

export function getTaskById(id) {
  return TASKS.find((task) => task.id === id);
}
