export {
  MEMORY_GOVERNANCE_PLAN_SYSTEM_PROMPT as WRITEBACK_MAINTENANCE_SYSTEM_PROMPT,
  MEMORY_GOVERNANCE_VERIFY_SYSTEM_PROMPT as WRITEBACK_GOVERNANCE_VERIFY_SYSTEM_PROMPT,
  MEMORY_WRITEBACK_REFINE_SYSTEM_PROMPT as WRITEBACK_REFINE_SYSTEM_PROMPT,
} from "../memory-orchestrator/prompts.js";
